[project]
name = "agent-cli"
version = "0.1.0"
description = "Minimal Claude Code with `Bash`/`Read`/`Write`/`Edit` tools, task planning, subagent orchestration, and skill system support."
readme = "README.md"
authors = [ { name = "sabertazimi", email = "sabertazimi@gmail.com" } ]
requires-python = ">=3.13"
dependencies = [
  "anthropic>=0.76.0",
  "python-dotenv>=1.2.1",
  "rich>=14.3.1",
]

[project.scripts]
agent-cli = "agent_cli:main"
ac = "agent_cli:main"

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[build-system]
requires = [ "uv_build>=0.9.27,<0.10.0" ]
build-backend = "uv_build"
